# Generated by Django 4.0.4 on 2022-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeDob', models.DateField(max_length=100)),
                ('employeeEmail', models.EmailField(max_length=100)),
                ('employeePhone', models.CharField(max_length=100)),
                ('employeeCode', models.CharField(max_length=100)),
                ('employeeAddress', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='employeeRegistratoin',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
