# Generated by Django 4.0.5 on 2022-06-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_employeedetail_rename_users_employeeregistratoin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employeeDetail',
        ),
    ]
