# Generated by Django 4.0.5 on 2022-06-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_delete_employeedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistratoin',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='employeeregistratoin',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeregistratoin',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeregistratoin',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeregistratoin',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
